### ISSUE TITLE
New-GuacamoleUser: Password not set

### ISSUE THREAD

**Issue by schulz-alexander** [hvoges/PoshGuacamole#1]
**Problem:**
If I create a new user with ```New-GuacamoleUser -Username testuser -Password testpass``` then the password ist not set and I can not login into guacamole

**Solution**
Change in New-GuacamoleUser.ps1 on line 73 from
```Password = $Password```
to
```password = $Password```

**Comment by hvoges** [comment]
Thank you for your comment. The issue is fixed now.
