### ISSUE TITLE
$PSBoundParameters doesn't include default parameter values

### ISSUE THREAD

**Issue by schulz-alexander** [hvoges/PoshGuacamole#2]
You use a switch Statement with $PSBoundParameters to fill the array for the webrequest, but $PSBoundParameters does not include the default parameters. 

For example, I have to use 
```
New-GuacamoleRdpConnection -Connectionname $user -UserName $pass -Password $pass -Hostname 10.30.10.30 -Domain schulung -ResizeMethod display-update -IgnoreCertificateWarning 'true' -ServerLayout 'de-de-qwertz' -RdpPort 3389
```
to dynamicaly resize the display, ignore the certificate, use German Layout and use port 3389.

If i just call 
```
New-GuacamoleRdpConnection -Connectionname $user -UserName $pass -Password $pass -Hostname 10.30.10.30 -Domain schulung
```
the values are not send to guacamole.

**Comment by hvoges** [comment]
Thank you for your feedback. I will look into the issue. There are some more, I am still finalizing the module and haven´t reached New-GuacamoleRdpConnection yet. I will Synchronize my changes tomorrow or so, I hope most issues should be fixed till then.

**Comment by schulz-alexander** [comment]
Thanks a lot for your work! It helps me a lot to automate a demosystem at work.

**Comment by hvoges** [comment]
You are very welcome. I need it for our own Guacamole-Installation. You can always thank me by recommending my company www.Netz-weise-it.training for IT-Trainings. ;-)

**Comment by hvoges** [comment]
I more or less created the cmdlet new from scratch. The issue should be fixed now.
